### PR TITLE
Add the swiftmailer

### LINKED ISSUE #53: FEATURE REQ:  Création Service d'Envoi d'email
**Description**  
Création d'un service qui permet d'envoyer des mails

### LINKED ISSUE #56: FEATURE REQ:  Add swiftmailer
**Description**  
add swift mailer bundle, to send the mail.

### PR DESCRIPTION
**Pull request by adjikpo**
# Description

Add swiftmailer for send the mail 

Resolve #56 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by romainmaucot** [comment]
Je peux merge

**Comment by romainmaucot** [comment]
?

**Comment by adjikpo** [comment]
Non pas encore

**Review by romainmaucot — APPROVED** [review]
Nice

**Pull request merged**
